In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('play_tennis.csv')

In [3]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data.drop(columns=['day'],inplace=True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
data.shape

(14, 5)

In [7]:
#1. outlook=sunny,temp=hot,humidity=high,wind=weak
# play or not?

In [8]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [9]:
py=9/14
pn=5/14

In [10]:
py

0.6428571428571429

In [11]:
pn

0.35714285714285715

In [12]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [14]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
pcn=1/5
phn=2/5
pmn=2/5

pcy=3/9
phy=2/9
pmy=4/9

In [16]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
phin=4/5
pnn=1/5

phiy=3/9
pny=6/9

In [18]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
pstn=3/5
pwn=2/5

psty=3/9
pwy=6/9

In [20]:
pyes=py*psy*phy*phiy*pwy

In [21]:
pyes

0.007054673721340388

In [22]:
pno=pn*psn*phn*phin*pwn

In [23]:
pno

0.02742857142857143

In [24]:
# here prob for yes< prob for no
# So NO PLAY.